plugins { id 'com.android.application' }

android {
    namespace 'com.wade.exynostools.layer'
    compileSdk 35

    defaultConfig {
        applicationId 'com.wade.exynostools.layer'
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    packaging {
        jniLibs {
            useLegacyPackaging = false
        }
    }
}
